### ISSUE TITLE
Express and SQL questions/wonderings

### ISSUE THREAD

**Issue by PhilWinchester** [React-Paint/react-paint#11]
@gittheking
@trevorpreston
@irwintsay

Annoying bug with my express server I can't see. Questions about storing a large array of integers in an sql table.

**Comment by gittheking** [comment]
@PhilWinchester Please be more specific and target the error, paste the code snippet in question, give us the error code you are receiving.

**Comment by PhilWinchester** [comment]
Error: 
  - Router.use() requires middleware function but got a Object
    - Checked and I have module.exports at the bottom of all the necessary files. 
- Server: 
  - `const app         = express();`
`const PORT        = process.argv[2] || process.env.port || 3000;`
`app.use(logger('dev'));`
`app.use(express.static(path.join(__dirname, 'dist')));`
`app.use(bodyParser.json());`
`app.use('/paint', require('./models/paint'));`
`app.listen(PORT, () => console.log('server here! listening on', PORT));`

- Routes: 
  - `const paint = require('express').Router();`
`const db = require('../models/paint');`
`const sendJSONResp = (req, res) => res.json(res.rows);`
`paint.route('/')`
  `.get(db.getAll, sendJSONResp)`
`module.exports = paint;`

- Models: 
  - `const db = require('./dbConnect');`
`module.exports = {`
  `getAll(req, res, next) {`
   ` db.any(`
      `SELECT * FROM canvas;`
      `)`
      `.then((canvas) => {`
        `res.rows = canvas;`
       ` next();`
     ` })`
      `.catch(error => next(error));`
 ` },`
`};`

**Comment by PhilWinchester** [comment]
@gittheking

**Comment by gittheking** [comment]
@PhilWinchester `app.use('/paint', require('./models/paint'));` should have `require('./routes/paint')`. You're giving it your model and not your route controller.
